[workspace]

[package]
name = "amadeus-parquet"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Apache Arrow <dev@arrow.apache.org>","Alec Mocatta <alec@mocatta.net>"]
categories = []
keywords = ["arrow", "parquet", "hadoop"]
description = """
An Apache Parquet implementation in Rust.
"""
repository = "https://github.com/alecmocatta/amadeus-parquet"
homepage = "https://github.com/alecmocatta/amadeus-parquet"
documentation = "https://docs.rs/amadeus-parquet/0.1.0"
readme = "README.md"
edition = "2018"

[badges]
azure-devops = { project = "alecmocatta/amadeus-parquet", pipeline = "tests" }
maintenance = { status = "actively-maintained" }

[dependencies]
parquet-format = "2.6.0"
parquet-derive = { version = "0.1.0", path = "./parquet-derive" }
quick-error = "1.2.2"
byteorder = "1.2"
thrift = "0.12.0"
snap = "0.2"
brotli = "3.3"
flate2 = "1.0.2"
lz4 = "1.23"
zstd = "0.4"
chrono = "0.4"
num-bigint = "0.2"
sum = "0.1"
linked-hash-map = "0.5"
fxhash = "0.2"

[dev-dependencies]
rand = "0.7"
